// ============================================================================
// TABLE PRIVILEGES
// ============================================================================

export const TablePrivileges = {
  CATALOG_MANAGE_ACCESS: 'CATALOG_MANAGE_ACCESS',
  TABLE_DROP: 'TABLE_DROP',
  TABLE_LIST: 'TABLE_LIST',
  TABLE_READ_PROPERTIES: 'TABLE_READ_PROPERTIES',
  TABLE_WRITE_PROPERTIES: 'TABLE_WRITE_PROPERTIES',
  TABLE_READ_DATA: 'TABLE_READ_DATA',
  TABLE_WRITE_DATA: 'TABLE_WRITE_DATA',
  TABLE_FULL_METADATA: 'TABLE_FULL_METADATA',
  TABLE_ATTACH_POLICY: 'TABLE_ATTACH_POLICY',
  TABLE_DETACH_POLICY: 'TABLE_DETACH_POLICY',
  TABLE_ASSIGN_UUID: 'TABLE_ASSIGN_UUID',
  TABLE_UPGRADE_FORMAT_VERSION: 'TABLE_UPGRADE_FORMAT_VERSION',
  TABLE_ADD_SCHEMA: 'TABLE_ADD_SCHEMA',
  TABLE_SET_CURRENT_SCHEMA: 'TABLE_SET_CURRENT_SCHEMA',
  TABLE_ADD_PARTITION_SPEC: 'TABLE_ADD_PARTITION_SPEC',
  TABLE_ADD_SORT_ORDER: 'TABLE_ADD_SORT_ORDER',
  TABLE_SET_DEFAULT_SORT_ORDER: 'TABLE_SET_DEFAULT_SORT_ORDER',
  TABLE_ADD_SNAPSHOT: 'TABLE_ADD_SNAPSHOT',
  TABLE_SET_SNAPSHOT_REF: 'TABLE_SET_SNAPSHOT_REF',
  TABLE_REMOVE_SNAPSHOTS: 'TABLE_REMOVE_SNAPSHOTS',
  TABLE_REMOVE_SNAPSHOT_REF: 'TABLE_REMOVE_SNAPSHOT_REF',
  TABLE_SET_LOCATION: 'TABLE_SET_LOCATION',
  TABLE_SET_PROPERTIES: 'TABLE_SET_PROPERTIES',
  TABLE_REMOVE_PROPERTIES: 'TABLE_REMOVE_PROPERTIES',
  TABLE_SET_STATISTICS: 'TABLE_SET_STATISTICS',
  TABLE_REMOVE_STATISTICS: 'TABLE_REMOVE_STATISTICS',
  TABLE_REMOVE_PARTITION_SPECS: 'TABLE_REMOVE_PARTITION_SPECS',
  TABLE_MANAGE_STRUCTURE: 'TABLE_MANAGE_STRUCTURE',
} as const;

export const TablePrivilegeDescriptions = {
  CATALOG_MANAGE_ACCESS: 'Includes the ability to grant or revoke privileges on objects in a catalog to catalog roles, and the ability to grant or revoke catalog roles to or from principal roles.',
  TABLE_DROP: 'Enables dropping a table from the catalog.',
  TABLE_LIST: 'Enables listing any table in the catalog.',
  TABLE_READ_PROPERTIES: 'Enables reading properties of the table.',
  TABLE_WRITE_PROPERTIES: 'Enables configuring properties for the table.',
  TABLE_READ_DATA: 'Enables reading data from the table by receiving short-lived read-only storage credentials from the catalog.',
  TABLE_WRITE_DATA: 'Enables writing data to the table by receiving short-lived read+write storage credentials from the catalog.',
  TABLE_FULL_METADATA: 'Grants all table privileges.',
  TABLE_ATTACH_POLICY: 'Enables attaching policy to a table.',
  TABLE_DETACH_POLICY: 'Enables detaching policy from a table.',
  TABLE_ASSIGN_UUID: 'Enables assigning a UUID to the table.',
  TABLE_UPGRADE_FORMAT_VERSION: 'Enables upgrading the table format version.',
  TABLE_ADD_SCHEMA: 'Enables adding a schema to the table.',
  TABLE_SET_CURRENT_SCHEMA: 'Enables setting the current schema for the table.',
  TABLE_ADD_PARTITION_SPEC: 'Enables adding a partition spec to the table.',
  TABLE_ADD_SORT_ORDER: 'Enables adding a sort order to the table.',
  TABLE_SET_DEFAULT_SORT_ORDER: 'Enables setting the default sort order for the table.',
  TABLE_ADD_SNAPSHOT: 'Enables adding a snapshot to the table.',
  TABLE_SET_SNAPSHOT_REF: 'Enables setting a snapshot reference for the table.',
  TABLE_REMOVE_SNAPSHOTS: 'Enables removing snapshots from the table.',
  TABLE_REMOVE_SNAPSHOT_REF: 'Enables removing snapshot references from the table.',
  TABLE_SET_LOCATION: 'Enables setting the location of the table.',
  TABLE_SET_PROPERTIES: 'Enables setting properties on the table.',
  TABLE_REMOVE_PROPERTIES: 'Enables removing properties from the table.',
  TABLE_SET_STATISTICS: 'Enables setting statistics on the table.',
  TABLE_REMOVE_STATISTICS: 'Enables removing statistics from the table.',
  TABLE_REMOVE_PARTITION_SPECS: 'Enables removing partition specs from the table.',
  TABLE_MANAGE_STRUCTURE: 'Enables managing the structure of the table.',
} as const;

// ============================================================================
// VIEW PRIVILEGES
// ============================================================================

export const ViewPrivileges = {
  CATALOG_MANAGE_ACCESS: 'CATALOG_MANAGE_ACCESS',
  VIEW_DROP: 'VIEW_DROP',
  VIEW_LIST: 'VIEW_LIST',
  VIEW_READ_PROPERTIES: 'VIEW_READ_PROPERTIES',
  VIEW_WRITE_PROPERTIES: 'VIEW_WRITE_PROPERTIES',
  VIEW_FULL_METADATA: 'VIEW_FULL_METADATA',
} as const;

export const ViewPrivilegeDescriptions = {
  CATALOG_MANAGE_ACCESS: 'Includes the ability to grant or revoke privileges on objects in a catalog to catalog roles, and the ability to grant or revoke catalog roles to or from principal roles.',
  VIEW_DROP: 'Enables dropping a view from the catalog.',
  VIEW_LIST: 'Enables listing any views in the catalog.',
  VIEW_READ_PROPERTIES: 'Enables reading all the view properties.',
  VIEW_WRITE_PROPERTIES: 'Enables configuring view properties.',
  VIEW_FULL_METADATA: 'Grants all view privileges.',
} as const;

// ============================================================================
// NAMESPACE PRIVILEGES
// ============================================================================

export const NamespacePrivileges = {
  CATALOG_MANAGE_ACCESS: 'CATALOG_MANAGE_ACCESS',
  CATALOG_MANAGE_CONTENT: 'CATALOG_MANAGE_CONTENT',
  CATALOG_MANAGE_METADATA: 'CATALOG_MANAGE_METADATA',
  NAMESPACE_CREATE: 'NAMESPACE_CREATE',
  TABLE_CREATE: 'TABLE_CREATE',
  VIEW_CREATE: 'VIEW_CREATE',
  NAMESPACE_DROP: 'NAMESPACE_DROP',
  TABLE_DROP: 'TABLE_DROP',
  VIEW_DROP: 'VIEW_DROP',
  NAMESPACE_LIST: 'NAMESPACE_LIST',
  TABLE_LIST: 'TABLE_LIST',
  VIEW_LIST: 'VIEW_LIST',
  NAMESPACE_READ_PROPERTIES: 'NAMESPACE_READ_PROPERTIES',
  TABLE_READ_PROPERTIES: 'TABLE_READ_PROPERTIES',
  VIEW_READ_PROPERTIES: 'VIEW_READ_PROPERTIES',
  NAMESPACE_WRITE_PROPERTIES: 'NAMESPACE_WRITE_PROPERTIES',
  TABLE_WRITE_PROPERTIES: 'TABLE_WRITE_PROPERTIES',
  VIEW_WRITE_PROPERTIES: 'VIEW_WRITE_PROPERTIES',
  TABLE_READ_DATA: 'TABLE_READ_DATA',
  TABLE_WRITE_DATA: 'TABLE_WRITE_DATA',
  NAMESPACE_FULL_METADATA: 'NAMESPACE_FULL_METADATA',
  TABLE_FULL_METADATA: 'TABLE_FULL_METADATA',
  VIEW_FULL_METADATA: 'VIEW_FULL_METADATA',
  POLICY_CREATE: 'POLICY_CREATE',
  POLICY_WRITE: 'POLICY_WRITE',
  POLICY_READ: 'POLICY_READ',
  POLICY_DROP: 'POLICY_DROP',
  POLICY_LIST: 'POLICY_LIST',
  POLICY_FULL_METADATA: 'POLICY_FULL_METADATA',
  NAMESPACE_ATTACH_POLICY: 'NAMESPACE_ATTACH_POLICY',
  NAMESPACE_DETACH_POLICY: 'NAMESPACE_DETACH_POLICY',
  TABLE_ASSIGN_UUID: 'TABLE_ASSIGN_UUID',
  TABLE_UPGRADE_FORMAT_VERSION: 'TABLE_UPGRADE_FORMAT_VERSION',
  TABLE_ADD_SCHEMA: 'TABLE_ADD_SCHEMA',
  TABLE_SET_CURRENT_SCHEMA: 'TABLE_SET_CURRENT_SCHEMA',
  TABLE_ADD_PARTITION_SPEC: 'TABLE_ADD_PARTITION_SPEC',
  TABLE_ADD_SORT_ORDER: 'TABLE_ADD_SORT_ORDER',
  TABLE_SET_DEFAULT_SORT_ORDER: 'TABLE_SET_DEFAULT_SORT_ORDER',
  TABLE_ADD_SNAPSHOT: 'TABLE_ADD_SNAPSHOT',
  TABLE_SET_SNAPSHOT_REF: 'TABLE_SET_SNAPSHOT_REF',
  TABLE_REMOVE_SNAPSHOTS: 'TABLE_REMOVE_SNAPSHOTS',
  TABLE_REMOVE_SNAPSHOT_REF: 'TABLE_REMOVE_SNAPSHOT_REF',
  TABLE_SET_LOCATION: 'TABLE_SET_LOCATION',
  TABLE_SET_PROPERTIES: 'TABLE_SET_PROPERTIES',
  TABLE_REMOVE_PROPERTIES: 'TABLE_REMOVE_PROPERTIES',
  TABLE_SET_STATISTICS: 'TABLE_SET_STATISTICS',
  TABLE_REMOVE_STATISTICS: 'TABLE_REMOVE_STATISTICS',
  TABLE_REMOVE_PARTITION_SPECS: 'TABLE_REMOVE_PARTITION_SPECS',
  TABLE_MANAGE_STRUCTURE: 'TABLE_MANAGE_STRUCTURE',
} as const;

export const NamespacePrivilegeDescriptions = {
  CATALOG_MANAGE_ACCESS: 'Includes the ability to grant or revoke privileges on objects in a catalog to catalog roles, and the ability to grant or revoke catalog roles to or from principal roles.',
  CATALOG_MANAGE_CONTENT: 'Enables full management of catalog content.',
  CATALOG_MANAGE_METADATA: 'Enables full management of the catalog, catalog roles, namespaces, and tables.',
  NAMESPACE_CREATE: 'Enables creating a namespace in a catalog.',
  TABLE_CREATE: 'Enables registering a table with the catalog.',
  VIEW_CREATE: 'Enables registering a view with the catalog.',
  NAMESPACE_DROP: 'Enables dropping the namespace from the catalog.',
  TABLE_DROP: 'Enables dropping a table from the catalog.',
  VIEW_DROP: 'Enables dropping a view from the catalog.',
  NAMESPACE_LIST: 'Enables listing any object in the namespace, including nested namespaces and tables.',
  TABLE_LIST: 'Enables listing any table in the catalog.',
  VIEW_LIST: 'Enables listing any views in the catalog.',
  NAMESPACE_READ_PROPERTIES: 'Enables reading all the namespace properties.',
  TABLE_READ_PROPERTIES: 'Enables reading properties of the table.',
  VIEW_READ_PROPERTIES: 'Enables reading all the view properties.',
  NAMESPACE_WRITE_PROPERTIES: 'Enables configuring namespace properties.',
  TABLE_WRITE_PROPERTIES: 'Enables configuring properties for the table.',
  VIEW_WRITE_PROPERTIES: 'Enables configuring view properties.',
  TABLE_READ_DATA: 'Enables reading data from the table by receiving short-lived read-only storage credentials from the catalog.',
  TABLE_WRITE_DATA: 'Enables writing data to the table by receiving short-lived read+write storage credentials from the catalog.',
  NAMESPACE_FULL_METADATA: 'Grants all namespace privileges.',
  TABLE_FULL_METADATA: 'Grants all table privileges.',
  VIEW_FULL_METADATA: 'Grants all view privileges.',
  POLICY_CREATE: 'Enables creating a policy under specified namespace.',
  POLICY_WRITE: 'Enables updating the policy details such as its content or description.',
  POLICY_READ: 'Enables reading policy content and metadata.',
  POLICY_DROP: 'Enables dropping a policy if it is not attached to any resource entity.',
  POLICY_LIST: 'Enables listing any policy from the catalog.',
  POLICY_FULL_METADATA: 'Grants all policy privileges.',
  NAMESPACE_ATTACH_POLICY: 'Enables attaching policy to a namespace.',
  NAMESPACE_DETACH_POLICY: 'Enables detaching policy from a namespace.',
  TABLE_ASSIGN_UUID: 'Enables assigning a UUID to the table.',
  TABLE_UPGRADE_FORMAT_VERSION: 'Enables upgrading the table format version.',
  TABLE_ADD_SCHEMA: 'Enables adding a schema to the table.',
  TABLE_SET_CURRENT_SCHEMA: 'Enables setting the current schema for the table.',
  TABLE_ADD_PARTITION_SPEC: 'Enables adding a partition spec to the table.',
  TABLE_ADD_SORT_ORDER: 'Enables adding a sort order to the table.',
  TABLE_SET_DEFAULT_SORT_ORDER: 'Enables setting the default sort order for the table.',
  TABLE_ADD_SNAPSHOT: 'Enables adding a snapshot to the table.',
  TABLE_SET_SNAPSHOT_REF: 'Enables setting a snapshot reference for the table.',
  TABLE_REMOVE_SNAPSHOTS: 'Enables removing snapshots from the table.',
  TABLE_REMOVE_SNAPSHOT_REF: 'Enables removing snapshot references from the table.',
  TABLE_SET_LOCATION: 'Enables setting the location of the table.',
  TABLE_SET_PROPERTIES: 'Enables setting properties on the table.',
  TABLE_REMOVE_PROPERTIES: 'Enables removing properties from the table.',
  TABLE_SET_STATISTICS: 'Enables setting statistics on the table.',
  TABLE_REMOVE_STATISTICS: 'Enables removing statistics from the table.',
  TABLE_REMOVE_PARTITION_SPECS: 'Enables removing partition specs from the table.',
  TABLE_MANAGE_STRUCTURE: 'Enables managing the structure of the table.',
} as const;

// ============================================================================
// CATALOG PRIVILEGES
// ============================================================================

export const CatalogPrivileges = {
  CATALOG_MANAGE_ACCESS: 'CATALOG_MANAGE_ACCESS',
  CATALOG_MANAGE_CONTENT: 'CATALOG_MANAGE_CONTENT',
  CATALOG_MANAGE_METADATA: 'CATALOG_MANAGE_METADATA',
  CATALOG_READ_PROPERTIES: 'CATALOG_READ_PROPERTIES',
  CATALOG_WRITE_PROPERTIES: 'CATALOG_WRITE_PROPERTIES',
  NAMESPACE_CREATE: 'NAMESPACE_CREATE',
  TABLE_CREATE: 'TABLE_CREATE',
  VIEW_CREATE: 'VIEW_CREATE',
  NAMESPACE_DROP: 'NAMESPACE_DROP',
  TABLE_DROP: 'TABLE_DROP',
  VIEW_DROP: 'VIEW_DROP',
  NAMESPACE_LIST: 'NAMESPACE_LIST',
  TABLE_LIST: 'TABLE_LIST',
  VIEW_LIST: 'VIEW_LIST',
  NAMESPACE_READ_PROPERTIES: 'NAMESPACE_READ_PROPERTIES',
  TABLE_READ_PROPERTIES: 'TABLE_READ_PROPERTIES',
  VIEW_READ_PROPERTIES: 'VIEW_READ_PROPERTIES',
  NAMESPACE_WRITE_PROPERTIES: 'NAMESPACE_WRITE_PROPERTIES',
  TABLE_WRITE_PROPERTIES: 'TABLE_WRITE_PROPERTIES',
  VIEW_WRITE_PROPERTIES: 'VIEW_WRITE_PROPERTIES',
  TABLE_READ_DATA: 'TABLE_READ_DATA',
  TABLE_WRITE_DATA: 'TABLE_WRITE_DATA',
  NAMESPACE_FULL_METADATA: 'NAMESPACE_FULL_METADATA',
  TABLE_FULL_METADATA: 'TABLE_FULL_METADATA',
  VIEW_FULL_METADATA: 'VIEW_FULL_METADATA',
  POLICY_CREATE: 'POLICY_CREATE',
  POLICY_WRITE: 'POLICY_WRITE',
  POLICY_READ: 'POLICY_READ',
  POLICY_DROP: 'POLICY_DROP',
  POLICY_LIST: 'POLICY_LIST',
  POLICY_FULL_METADATA: 'POLICY_FULL_METADATA',
  CATALOG_ATTACH_POLICY: 'CATALOG_ATTACH_POLICY',
  CATALOG_DETACH_POLICY: 'CATALOG_DETACH_POLICY',
  TABLE_ASSIGN_UUID: 'TABLE_ASSIGN_UUID',
  TABLE_UPGRADE_FORMAT_VERSION: 'TABLE_UPGRADE_FORMAT_VERSION',
  TABLE_ADD_SCHEMA: 'TABLE_ADD_SCHEMA',
  TABLE_SET_CURRENT_SCHEMA: 'TABLE_SET_CURRENT_SCHEMA',
  TABLE_ADD_PARTITION_SPEC: 'TABLE_ADD_PARTITION_SPEC',
  TABLE_ADD_SORT_ORDER: 'TABLE_ADD_SORT_ORDER',
  TABLE_SET_DEFAULT_SORT_ORDER: 'TABLE_SET_DEFAULT_SORT_ORDER',
  TABLE_ADD_SNAPSHOT: 'TABLE_ADD_SNAPSHOT',
  TABLE_SET_SNAPSHOT_REF: 'TABLE_SET_SNAPSHOT_REF',
  TABLE_REMOVE_SNAPSHOTS: 'TABLE_REMOVE_SNAPSHOTS',
  TABLE_REMOVE_SNAPSHOT_REF: 'TABLE_REMOVE_SNAPSHOT_REF',
  TABLE_SET_LOCATION: 'TABLE_SET_LOCATION',
  TABLE_SET_PROPERTIES: 'TABLE_SET_PROPERTIES',
  TABLE_REMOVE_PROPERTIES: 'TABLE_REMOVE_PROPERTIES',
  TABLE_SET_STATISTICS: 'TABLE_SET_STATISTICS',
  TABLE_REMOVE_STATISTICS: 'TABLE_REMOVE_STATISTICS',
  TABLE_REMOVE_PARTITION_SPECS: 'TABLE_REMOVE_PARTITION_SPECS',
  TABLE_MANAGE_STRUCTURE: 'TABLE_MANAGE_STRUCTURE',
} as const;

export const CatalogPrivilegeDescriptions = {
  CATALOG_MANAGE_ACCESS: 'Includes the ability to grant or revoke privileges on objects in a catalog to catalog roles, and the ability to grant or revoke catalog roles to or from principal roles.',
  CATALOG_MANAGE_CONTENT: 'Enables full management of catalog content.',
  CATALOG_MANAGE_METADATA: 'Enables full management of the catalog, catalog roles, namespaces, and tables.',
  CATALOG_READ_PROPERTIES: 'Enables listing catalogs and reading properties of the catalog.',
  CATALOG_WRITE_PROPERTIES: 'Enables configuring catalog properties.',
  NAMESPACE_CREATE: 'Enables creating a namespace in a catalog.',
  TABLE_CREATE: 'Enables registering a table with the catalog.',
  VIEW_CREATE: 'Enables registering a view with the catalog.',
  NAMESPACE_DROP: 'Enables dropping the namespace from the catalog.',
  TABLE_DROP: 'Enables dropping a table from the catalog.',
  VIEW_DROP: 'Enables dropping a view from the catalog.',
  NAMESPACE_LIST: 'Enables listing any object in the namespace, including nested namespaces and tables.',
  TABLE_LIST: 'Enables listing any table in the catalog.',
  VIEW_LIST: 'Enables listing any views in the catalog.',
  NAMESPACE_READ_PROPERTIES: 'Enables reading all the namespace properties.',
  TABLE_READ_PROPERTIES: 'Enables reading properties of the table.',
  VIEW_READ_PROPERTIES: 'Enables reading all the view properties.',
  NAMESPACE_WRITE_PROPERTIES: 'Enables configuring namespace properties.',
  TABLE_WRITE_PROPERTIES: 'Enables configuring properties for the table.',
  VIEW_WRITE_PROPERTIES: 'Enables configuring view properties.',
  TABLE_READ_DATA: 'Enables reading data from the table by receiving short-lived read-only storage credentials from the catalog.',
  TABLE_WRITE_DATA: 'Enables writing data to the table by receiving short-lived read+write storage credentials from the catalog.',
  NAMESPACE_FULL_METADATA: 'Grants all namespace privileges.',
  TABLE_FULL_METADATA: 'Grants all table privileges.',
  VIEW_FULL_METADATA: 'Grants all view privileges.',
  POLICY_CREATE: 'Enables creating a policy under specified namespace.',
  POLICY_WRITE: 'Enables updating the policy details such as its content or description.',
  POLICY_READ: 'Enables reading policy content and metadata.',
  POLICY_DROP: 'Enables dropping a policy if it is not attached to any resource entity.',
  POLICY_LIST: 'Enables listing any policy from the catalog.',
  POLICY_FULL_METADATA: 'Grants all policy privileges.',
  CATALOG_ATTACH_POLICY: 'Enables attaching policy to a catalog.',
  CATALOG_DETACH_POLICY: 'Enables detaching policy from a catalog.',
  TABLE_ASSIGN_UUID: 'Enables assigning a UUID to the table.',
  TABLE_UPGRADE_FORMAT_VERSION: 'Enables upgrading the table format version.',
  TABLE_ADD_SCHEMA: 'Enables adding a schema to the table.',
  TABLE_SET_CURRENT_SCHEMA: 'Enables setting the current schema for the table.',
  TABLE_ADD_PARTITION_SPEC: 'Enables adding a partition spec to the table.',
  TABLE_ADD_SORT_ORDER: 'Enables adding a sort order to the table.',
  TABLE_SET_DEFAULT_SORT_ORDER: 'Enables setting the default sort order for the table.',
  TABLE_ADD_SNAPSHOT: 'Enables adding a snapshot to the table.',
  TABLE_SET_SNAPSHOT_REF: 'Enables setting a snapshot reference for the table.',
  TABLE_REMOVE_SNAPSHOTS: 'Enables removing snapshots from the table.',
  TABLE_REMOVE_SNAPSHOT_REF: 'Enables removing snapshot references from the table.',
  TABLE_SET_LOCATION: 'Enables setting the location of the table.',
  TABLE_SET_PROPERTIES: 'Enables setting properties on the table.',
  TABLE_REMOVE_PROPERTIES: 'Enables removing properties from the table.',
  TABLE_SET_STATISTICS: 'Enables setting statistics on the table.',
  TABLE_REMOVE_STATISTICS: 'Enables removing statistics from the table.',
  TABLE_REMOVE_PARTITION_SPECS: 'Enables removing partition specs from the table.',
  TABLE_MANAGE_STRUCTURE: 'Enables managing the structure of the table.',
} as const;

// ============================================================================
// POLICY PRIVILEGES
// ============================================================================

export const PolicyPrivileges = {
  CATALOG_MANAGE_ACCESS: 'CATALOG_MANAGE_ACCESS',
  POLICY_READ: 'POLICY_READ',
  POLICY_DROP: 'POLICY_DROP',
  POLICY_WRITE: 'POLICY_WRITE',
  POLICY_LIST: 'POLICY_LIST',
  POLICY_FULL_METADATA: 'POLICY_FULL_METADATA',
  POLICY_ATTACH: 'POLICY_ATTACH',
  POLICY_DETACH: 'POLICY_DETACH',
} as const;

export const PolicyPrivilegeDescriptions = {
  CATALOG_MANAGE_ACCESS: 'Includes the ability to grant or revoke privileges on objects in a catalog to catalog roles, and the ability to grant or revoke catalog roles to or from principal roles.',
  POLICY_READ: 'Enables reading policy content and metadata.',
  POLICY_DROP: 'Enables dropping a policy if it is not attached to any resource entity.',
  POLICY_WRITE: 'Enables updating the policy details such as its content or description.',
  POLICY_LIST: 'Enables listing any policy from the catalog.',
  POLICY_FULL_METADATA: 'Grants all policy privileges.',
  POLICY_ATTACH: 'Enables policy to be attached to entities.',
  POLICY_DETACH: 'Enables policy to be detached from entities.',
} as const;

